/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const ACTIVATE_ACCOUNT_DISCRIMINATOR = 7;

export function getActivateAccountDiscriminatorBytes() {
  return getU8Encoder().encode(ACTIVATE_ACCOUNT_DISCRIMINATOR);
}

export type ActivateAccountInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSystemProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountBump extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountUserId extends string | AccountMeta<string> = string,
  TAccountRevenueMint extends string | AccountMeta<string> = string,
  TAccountRevenueSenderAta extends string | AccountMeta<string> = string,
  TAccountRevenueAppAta extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountBump extends string
        ? ReadonlyAccount<TAccountBump>
        : TAccountBump,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountUserId extends string
        ? WritableAccount<TAccountUserId>
        : TAccountUserId,
      TAccountRevenueMint extends string
        ? ReadonlyAccount<TAccountRevenueMint>
        : TAccountRevenueMint,
      TAccountRevenueSenderAta extends string
        ? WritableAccount<TAccountRevenueSenderAta>
        : TAccountRevenueSenderAta,
      TAccountRevenueAppAta extends string
        ? WritableAccount<TAccountRevenueAppAta>
        : TAccountRevenueAppAta,
      ...TRemainingAccounts,
    ]
  >;

export type ActivateAccountInstructionData = { discriminator: number };

export type ActivateAccountInstructionDataArgs = {};

export function getActivateAccountInstructionDataEncoder(): FixedSizeEncoder<ActivateAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: ACTIVATE_ACCOUNT_DISCRIMINATOR })
  );
}

export function getActivateAccountInstructionDataDecoder(): FixedSizeDecoder<ActivateAccountInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getActivateAccountInstructionDataCodec(): FixedSizeCodec<
  ActivateAccountInstructionDataArgs,
  ActivateAccountInstructionData
> {
  return combineCodec(
    getActivateAccountInstructionDataEncoder(),
    getActivateAccountInstructionDataDecoder()
  );
}

export type ActivateAccountInput<
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSender extends string = string,
  TAccountBump extends string = string,
  TAccountConfig extends string = string,
  TAccountUserId extends string = string,
  TAccountRevenueMint extends string = string,
  TAccountRevenueSenderAta extends string = string,
  TAccountRevenueAppAta extends string = string,
> = {
  systemProgram: Address<TAccountSystemProgram>;
  tokenProgram: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  sender: TransactionSigner<TAccountSender>;
  bump: Address<TAccountBump>;
  config: Address<TAccountConfig>;
  userId: Address<TAccountUserId>;
  revenueMint: Address<TAccountRevenueMint>;
  revenueSenderAta: Address<TAccountRevenueSenderAta>;
  revenueAppAta: Address<TAccountRevenueAppAta>;
};

export function getActivateAccountInstruction<
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSender extends string,
  TAccountBump extends string,
  TAccountConfig extends string,
  TAccountUserId extends string,
  TAccountRevenueMint extends string,
  TAccountRevenueSenderAta extends string,
  TAccountRevenueAppAta extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: ActivateAccountInput<
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserId,
    TAccountRevenueMint,
    TAccountRevenueSenderAta,
    TAccountRevenueAppAta
  >,
  config?: { programAddress?: TProgramAddress }
): ActivateAccountInstruction<
  TProgramAddress,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSender,
  TAccountBump,
  TAccountConfig,
  TAccountUserId,
  TAccountRevenueMint,
  TAccountRevenueSenderAta,
  TAccountRevenueAppAta
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    sender: { value: input.sender ?? null, isWritable: true },
    bump: { value: input.bump ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    userId: { value: input.userId ?? null, isWritable: true },
    revenueMint: { value: input.revenueMint ?? null, isWritable: false },
    revenueSenderAta: {
      value: input.revenueSenderAta ?? null,
      isWritable: true,
    },
    revenueAppAta: { value: input.revenueAppAta ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.bump),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.userId),
      getAccountMeta(accounts.revenueMint),
      getAccountMeta(accounts.revenueSenderAta),
      getAccountMeta(accounts.revenueAppAta),
    ],
    data: getActivateAccountInstructionDataEncoder().encode({}),
    programAddress,
  } as ActivateAccountInstruction<
    TProgramAddress,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserId,
    TAccountRevenueMint,
    TAccountRevenueSenderAta,
    TAccountRevenueAppAta
  >);
}

export type ParsedActivateAccountInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    systemProgram: TAccountMetas[0];
    tokenProgram: TAccountMetas[1];
    associatedTokenProgram: TAccountMetas[2];
    sender: TAccountMetas[3];
    bump: TAccountMetas[4];
    config: TAccountMetas[5];
    userId: TAccountMetas[6];
    revenueMint: TAccountMetas[7];
    revenueSenderAta: TAccountMetas[8];
    revenueAppAta: TAccountMetas[9];
  };
  data: ActivateAccountInstructionData;
};

export function parseActivateAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedActivateAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      sender: getNextAccount(),
      bump: getNextAccount(),
      config: getNextAccount(),
      userId: getNextAccount(),
      revenueMint: getNextAccount(),
      revenueSenderAta: getNextAccount(),
      revenueAppAta: getNextAccount(),
    },
    data: getActivateAccountInstructionDataDecoder().decode(instruction.data),
  };
}
