/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from 'gill';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CONFIRM_ACCOUNT_ROTATION_DISCRIMINATOR = 10;

export function getConfirmAccountRotationDiscriminatorBytes() {
  return getU8Encoder().encode(CONFIRM_ACCOUNT_ROTATION_DISCRIMINATOR);
}

export type ConfirmAccountRotationInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSystemProgram extends string | AccountMeta<string> = string,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountUserIdPre extends string | AccountMeta<string> = string,
  TAccountUserId extends string | AccountMeta<string> = string,
  TAccountUserRotationState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountUserIdPre extends string
        ? WritableAccount<TAccountUserIdPre>
        : TAccountUserIdPre,
      TAccountUserId extends string
        ? WritableAccount<TAccountUserId>
        : TAccountUserId,
      TAccountUserRotationState extends string
        ? WritableAccount<TAccountUserRotationState>
        : TAccountUserRotationState,
      ...TRemainingAccounts,
    ]
  >;

export type ConfirmAccountRotationInstructionData = { discriminator: number };

export type ConfirmAccountRotationInstructionDataArgs = {};

export function getConfirmAccountRotationInstructionDataEncoder(): FixedSizeEncoder<ConfirmAccountRotationInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: CONFIRM_ACCOUNT_ROTATION_DISCRIMINATOR,
    })
  );
}

export function getConfirmAccountRotationInstructionDataDecoder(): FixedSizeDecoder<ConfirmAccountRotationInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getConfirmAccountRotationInstructionDataCodec(): FixedSizeCodec<
  ConfirmAccountRotationInstructionDataArgs,
  ConfirmAccountRotationInstructionData
> {
  return combineCodec(
    getConfirmAccountRotationInstructionDataEncoder(),
    getConfirmAccountRotationInstructionDataDecoder()
  );
}

export type ConfirmAccountRotationInput<
  TAccountSystemProgram extends string = string,
  TAccountSender extends string = string,
  TAccountUserIdPre extends string = string,
  TAccountUserId extends string = string,
  TAccountUserRotationState extends string = string,
> = {
  systemProgram: Address<TAccountSystemProgram>;
  sender: TransactionSigner<TAccountSender>;
  userIdPre: Address<TAccountUserIdPre>;
  userId: Address<TAccountUserId>;
  userRotationState: Address<TAccountUserRotationState>;
};

export function getConfirmAccountRotationInstruction<
  TAccountSystemProgram extends string,
  TAccountSender extends string,
  TAccountUserIdPre extends string,
  TAccountUserId extends string,
  TAccountUserRotationState extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: ConfirmAccountRotationInput<
    TAccountSystemProgram,
    TAccountSender,
    TAccountUserIdPre,
    TAccountUserId,
    TAccountUserRotationState
  >,
  config?: { programAddress?: TProgramAddress }
): ConfirmAccountRotationInstruction<
  TProgramAddress,
  TAccountSystemProgram,
  TAccountSender,
  TAccountUserIdPre,
  TAccountUserId,
  TAccountUserRotationState
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    sender: { value: input.sender ?? null, isWritable: true },
    userIdPre: { value: input.userIdPre ?? null, isWritable: true },
    userId: { value: input.userId ?? null, isWritable: true },
    userRotationState: {
      value: input.userRotationState ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.userIdPre),
      getAccountMeta(accounts.userId),
      getAccountMeta(accounts.userRotationState),
    ],
    data: getConfirmAccountRotationInstructionDataEncoder().encode({}),
    programAddress,
  } as ConfirmAccountRotationInstruction<
    TProgramAddress,
    TAccountSystemProgram,
    TAccountSender,
    TAccountUserIdPre,
    TAccountUserId,
    TAccountUserRotationState
  >);
}

export type ParsedConfirmAccountRotationInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    systemProgram: TAccountMetas[0];
    sender: TAccountMetas[1];
    userIdPre: TAccountMetas[2];
    userId: TAccountMetas[3];
    userRotationState: TAccountMetas[4];
  };
  data: ConfirmAccountRotationInstructionData;
};

export function parseConfirmAccountRotationInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedConfirmAccountRotationInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      systemProgram: getNextAccount(),
      sender: getNextAccount(),
      userIdPre: getNextAccount(),
      userId: getNextAccount(),
      userRotationState: getNextAccount(),
    },
    data: getConfirmAccountRotationInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
