/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from 'gill';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CONFIRM_ADMIN_ROTATION_DISCRIMINATOR = 2;

export function getConfirmAdminRotationDiscriminatorBytes() {
  return getU8Encoder().encode(CONFIRM_ADMIN_ROTATION_DISCRIMINATOR);
}

export type ConfirmAdminRotationInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAdminRotationState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAdminRotationState extends string
        ? WritableAccount<TAccountAdminRotationState>
        : TAccountAdminRotationState,
      ...TRemainingAccounts,
    ]
  >;

export type ConfirmAdminRotationInstructionData = { discriminator: number };

export type ConfirmAdminRotationInstructionDataArgs = {};

export function getConfirmAdminRotationInstructionDataEncoder(): FixedSizeEncoder<ConfirmAdminRotationInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: CONFIRM_ADMIN_ROTATION_DISCRIMINATOR,
    })
  );
}

export function getConfirmAdminRotationInstructionDataDecoder(): FixedSizeDecoder<ConfirmAdminRotationInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getConfirmAdminRotationInstructionDataCodec(): FixedSizeCodec<
  ConfirmAdminRotationInstructionDataArgs,
  ConfirmAdminRotationInstructionData
> {
  return combineCodec(
    getConfirmAdminRotationInstructionDataEncoder(),
    getConfirmAdminRotationInstructionDataDecoder()
  );
}

export type ConfirmAdminRotationInput<
  TAccountSender extends string = string,
  TAccountConfig extends string = string,
  TAccountAdminRotationState extends string = string,
> = {
  sender: TransactionSigner<TAccountSender>;
  config: Address<TAccountConfig>;
  adminRotationState: Address<TAccountAdminRotationState>;
};

export function getConfirmAdminRotationInstruction<
  TAccountSender extends string,
  TAccountConfig extends string,
  TAccountAdminRotationState extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: ConfirmAdminRotationInput<
    TAccountSender,
    TAccountConfig,
    TAccountAdminRotationState
  >,
  config?: { programAddress?: TProgramAddress }
): ConfirmAdminRotationInstruction<
  TProgramAddress,
  TAccountSender,
  TAccountConfig,
  TAccountAdminRotationState
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sender: { value: input.sender ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    adminRotationState: {
      value: input.adminRotationState ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.adminRotationState),
    ],
    data: getConfirmAdminRotationInstructionDataEncoder().encode({}),
    programAddress,
  } as ConfirmAdminRotationInstruction<
    TProgramAddress,
    TAccountSender,
    TAccountConfig,
    TAccountAdminRotationState
  >);
}

export type ParsedConfirmAdminRotationInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    sender: TAccountMetas[0];
    config: TAccountMetas[1];
    adminRotationState: TAccountMetas[2];
  };
  data: ConfirmAdminRotationInstructionData;
};

export function parseConfirmAdminRotationInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedConfirmAdminRotationInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      sender: getNextAccount(),
      config: getNextAccount(),
      adminRotationState: getNextAccount(),
    },
    data: getConfirmAdminRotationInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
