/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getAssetItemDecoder,
  getAssetItemEncoder,
  getBitFieldDecoder,
  getBitFieldEncoder,
  getRangeDecoder,
  getRangeEncoder,
  getUint32Decoder,
  getUint32Encoder,
  type AssetItem,
  type AssetItemArgs,
  type BitField,
  type BitFieldArgs,
  type Range,
  type RangeArgs,
  type Uint32,
  type Uint32Args,
} from '../types';

export const INIT_DISCRIMINATOR = 0;

export function getInitDiscriminatorBytes() {
  return getU8Encoder().encode(INIT_DISCRIMINATOR);
}

export type InitInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSystemProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountBump extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountUserCounter extends string | AccountMeta<string> = string,
  TAccountAdminRotationState extends string | AccountMeta<string> = string,
  TAccountRevenueMint extends string | AccountMeta<string> = string,
  TAccountRevenueAppAta extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountBump extends string
        ? WritableAccount<TAccountBump>
        : TAccountBump,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountUserCounter extends string
        ? WritableAccount<TAccountUserCounter>
        : TAccountUserCounter,
      TAccountAdminRotationState extends string
        ? WritableAccount<TAccountAdminRotationState>
        : TAccountAdminRotationState,
      TAccountRevenueMint extends string
        ? ReadonlyAccount<TAccountRevenueMint>
        : TAccountRevenueMint,
      TAccountRevenueAppAta extends string
        ? WritableAccount<TAccountRevenueAppAta>
        : TAccountRevenueAppAta,
      ...TRemainingAccounts,
    ]
  >;

export type InitInstructionData = {
  discriminator: number;
  flags: BitField;
  rotationTimeout: Uint32;
  accountRegistrationFee: AssetItem;
  accountDataSizeRange: Range;
};

export type InitInstructionDataArgs = {
  flags: BitFieldArgs;
  rotationTimeout: Uint32Args;
  accountRegistrationFee: AssetItemArgs;
  accountDataSizeRange: RangeArgs;
};

export function getInitInstructionDataEncoder(): Encoder<InitInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['flags', getBitFieldEncoder()],
      ['rotationTimeout', getUint32Encoder()],
      ['accountRegistrationFee', getAssetItemEncoder()],
      ['accountDataSizeRange', getRangeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_DISCRIMINATOR })
  );
}

export function getInitInstructionDataDecoder(): Decoder<InitInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['flags', getBitFieldDecoder()],
    ['rotationTimeout', getUint32Decoder()],
    ['accountRegistrationFee', getAssetItemDecoder()],
    ['accountDataSizeRange', getRangeDecoder()],
  ]);
}

export function getInitInstructionDataCodec(): Codec<
  InitInstructionDataArgs,
  InitInstructionData
> {
  return combineCodec(
    getInitInstructionDataEncoder(),
    getInitInstructionDataDecoder()
  );
}

export type InitInput<
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSender extends string = string,
  TAccountBump extends string = string,
  TAccountConfig extends string = string,
  TAccountUserCounter extends string = string,
  TAccountAdminRotationState extends string = string,
  TAccountRevenueMint extends string = string,
  TAccountRevenueAppAta extends string = string,
> = {
  systemProgram: Address<TAccountSystemProgram>;
  tokenProgram: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  sender: TransactionSigner<TAccountSender>;
  bump: Address<TAccountBump>;
  config: Address<TAccountConfig>;
  userCounter: Address<TAccountUserCounter>;
  adminRotationState: Address<TAccountAdminRotationState>;
  revenueMint: Address<TAccountRevenueMint>;
  revenueAppAta: Address<TAccountRevenueAppAta>;
  flags: InitInstructionDataArgs['flags'];
  rotationTimeout: InitInstructionDataArgs['rotationTimeout'];
  accountRegistrationFee: InitInstructionDataArgs['accountRegistrationFee'];
  accountDataSizeRange: InitInstructionDataArgs['accountDataSizeRange'];
};

export function getInitInstruction<
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSender extends string,
  TAccountBump extends string,
  TAccountConfig extends string,
  TAccountUserCounter extends string,
  TAccountAdminRotationState extends string,
  TAccountRevenueMint extends string,
  TAccountRevenueAppAta extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: InitInput<
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserCounter,
    TAccountAdminRotationState,
    TAccountRevenueMint,
    TAccountRevenueAppAta
  >,
  config?: { programAddress?: TProgramAddress }
): InitInstruction<
  TProgramAddress,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSender,
  TAccountBump,
  TAccountConfig,
  TAccountUserCounter,
  TAccountAdminRotationState,
  TAccountRevenueMint,
  TAccountRevenueAppAta
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    sender: { value: input.sender ?? null, isWritable: true },
    bump: { value: input.bump ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    userCounter: { value: input.userCounter ?? null, isWritable: true },
    adminRotationState: {
      value: input.adminRotationState ?? null,
      isWritable: true,
    },
    revenueMint: { value: input.revenueMint ?? null, isWritable: false },
    revenueAppAta: { value: input.revenueAppAta ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.bump),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.userCounter),
      getAccountMeta(accounts.adminRotationState),
      getAccountMeta(accounts.revenueMint),
      getAccountMeta(accounts.revenueAppAta),
    ],
    data: getInitInstructionDataEncoder().encode(
      args as InitInstructionDataArgs
    ),
    programAddress,
  } as InitInstruction<
    TProgramAddress,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserCounter,
    TAccountAdminRotationState,
    TAccountRevenueMint,
    TAccountRevenueAppAta
  >);
}

export type ParsedInitInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    systemProgram: TAccountMetas[0];
    tokenProgram: TAccountMetas[1];
    associatedTokenProgram: TAccountMetas[2];
    sender: TAccountMetas[3];
    bump: TAccountMetas[4];
    config: TAccountMetas[5];
    userCounter: TAccountMetas[6];
    adminRotationState: TAccountMetas[7];
    revenueMint: TAccountMetas[8];
    revenueAppAta: TAccountMetas[9];
  };
  data: InitInstructionData;
};

export function parseInitInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      sender: getNextAccount(),
      bump: getNextAccount(),
      config: getNextAccount(),
      userCounter: getNextAccount(),
      adminRotationState: getNextAccount(),
      revenueMint: getNextAccount(),
      revenueAppAta: getNextAccount(),
    },
    data: getInitInstructionDataDecoder().decode(instruction.data),
  };
}
