/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getUint32Decoder,
  getUint32Encoder,
  type Uint32,
  type Uint32Args,
} from '../types';

export const REOPEN_ACCOUNT_DISCRIMINATOR = 6;

export function getReopenAccountDiscriminatorBytes() {
  return getU8Encoder().encode(REOPEN_ACCOUNT_DISCRIMINATOR);
}

export type ReopenAccountInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSystemProgram extends string | AccountMeta<string> = string,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountBump extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountUserId extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountUserRotationState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountBump extends string
        ? ReadonlyAccount<TAccountBump>
        : TAccountBump,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountUserId extends string
        ? WritableAccount<TAccountUserId>
        : TAccountUserId,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountUserRotationState extends string
        ? WritableAccount<TAccountUserRotationState>
        : TAccountUserRotationState,
      ...TRemainingAccounts,
    ]
  >;

export type ReopenAccountInstructionData = {
  discriminator: number;
  maxDataSize: Uint32;
};

export type ReopenAccountInstructionDataArgs = { maxDataSize: Uint32Args };

export function getReopenAccountInstructionDataEncoder(): Encoder<ReopenAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['maxDataSize', getUint32Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REOPEN_ACCOUNT_DISCRIMINATOR })
  );
}

export function getReopenAccountInstructionDataDecoder(): Decoder<ReopenAccountInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['maxDataSize', getUint32Decoder()],
  ]);
}

export function getReopenAccountInstructionDataCodec(): Codec<
  ReopenAccountInstructionDataArgs,
  ReopenAccountInstructionData
> {
  return combineCodec(
    getReopenAccountInstructionDataEncoder(),
    getReopenAccountInstructionDataDecoder()
  );
}

export type ReopenAccountInput<
  TAccountSystemProgram extends string = string,
  TAccountSender extends string = string,
  TAccountBump extends string = string,
  TAccountConfig extends string = string,
  TAccountUserId extends string = string,
  TAccountUserAccount extends string = string,
  TAccountUserRotationState extends string = string,
> = {
  systemProgram: Address<TAccountSystemProgram>;
  sender: TransactionSigner<TAccountSender>;
  bump: Address<TAccountBump>;
  config: Address<TAccountConfig>;
  userId: Address<TAccountUserId>;
  userAccount: Address<TAccountUserAccount>;
  userRotationState: Address<TAccountUserRotationState>;
  maxDataSize: ReopenAccountInstructionDataArgs['maxDataSize'];
};

export function getReopenAccountInstruction<
  TAccountSystemProgram extends string,
  TAccountSender extends string,
  TAccountBump extends string,
  TAccountConfig extends string,
  TAccountUserId extends string,
  TAccountUserAccount extends string,
  TAccountUserRotationState extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: ReopenAccountInput<
    TAccountSystemProgram,
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserId,
    TAccountUserAccount,
    TAccountUserRotationState
  >,
  config?: { programAddress?: TProgramAddress }
): ReopenAccountInstruction<
  TProgramAddress,
  TAccountSystemProgram,
  TAccountSender,
  TAccountBump,
  TAccountConfig,
  TAccountUserId,
  TAccountUserAccount,
  TAccountUserRotationState
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    sender: { value: input.sender ?? null, isWritable: true },
    bump: { value: input.bump ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    userId: { value: input.userId ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    userRotationState: {
      value: input.userRotationState ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.bump),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.userId),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.userRotationState),
    ],
    data: getReopenAccountInstructionDataEncoder().encode(
      args as ReopenAccountInstructionDataArgs
    ),
    programAddress,
  } as ReopenAccountInstruction<
    TProgramAddress,
    TAccountSystemProgram,
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserId,
    TAccountUserAccount,
    TAccountUserRotationState
  >);
}

export type ParsedReopenAccountInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    systemProgram: TAccountMetas[0];
    sender: TAccountMetas[1];
    bump: TAccountMetas[2];
    config: TAccountMetas[3];
    userId: TAccountMetas[4];
    userAccount: TAccountMetas[5];
    userRotationState: TAccountMetas[6];
  };
  data: ReopenAccountInstructionData;
};

export function parseReopenAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedReopenAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      systemProgram: getNextAccount(),
      sender: getNextAccount(),
      bump: getNextAccount(),
      config: getNextAccount(),
      userId: getNextAccount(),
      userAccount: getNextAccount(),
      userRotationState: getNextAccount(),
    },
    data: getReopenAccountInstructionDataDecoder().decode(instruction.data),
  };
}
