/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REQUEST_ACCOUNT_ROTATION_DISCRIMINATOR = 9;

export function getRequestAccountRotationDiscriminatorBytes() {
  return getU8Encoder().encode(REQUEST_ACCOUNT_ROTATION_DISCRIMINATOR);
}

export type RequestAccountRotationInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountBump extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountUserId extends string | AccountMeta<string> = string,
  TAccountUserRotationState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountBump extends string
        ? ReadonlyAccount<TAccountBump>
        : TAccountBump,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountUserId extends string
        ? ReadonlyAccount<TAccountUserId>
        : TAccountUserId,
      TAccountUserRotationState extends string
        ? WritableAccount<TAccountUserRotationState>
        : TAccountUserRotationState,
      ...TRemainingAccounts,
    ]
  >;

export type RequestAccountRotationInstructionData = {
  discriminator: number;
  newOwner: Address;
};

export type RequestAccountRotationInstructionDataArgs = { newOwner: Address };

export function getRequestAccountRotationInstructionDataEncoder(): FixedSizeEncoder<RequestAccountRotationInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['newOwner', getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: REQUEST_ACCOUNT_ROTATION_DISCRIMINATOR,
    })
  );
}

export function getRequestAccountRotationInstructionDataDecoder(): FixedSizeDecoder<RequestAccountRotationInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['newOwner', getAddressDecoder()],
  ]);
}

export function getRequestAccountRotationInstructionDataCodec(): FixedSizeCodec<
  RequestAccountRotationInstructionDataArgs,
  RequestAccountRotationInstructionData
> {
  return combineCodec(
    getRequestAccountRotationInstructionDataEncoder(),
    getRequestAccountRotationInstructionDataDecoder()
  );
}

export type RequestAccountRotationInput<
  TAccountSender extends string = string,
  TAccountBump extends string = string,
  TAccountConfig extends string = string,
  TAccountUserId extends string = string,
  TAccountUserRotationState extends string = string,
> = {
  sender: TransactionSigner<TAccountSender>;
  bump: Address<TAccountBump>;
  config: Address<TAccountConfig>;
  userId: Address<TAccountUserId>;
  userRotationState: Address<TAccountUserRotationState>;
  newOwner: RequestAccountRotationInstructionDataArgs['newOwner'];
};

export function getRequestAccountRotationInstruction<
  TAccountSender extends string,
  TAccountBump extends string,
  TAccountConfig extends string,
  TAccountUserId extends string,
  TAccountUserRotationState extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: RequestAccountRotationInput<
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserId,
    TAccountUserRotationState
  >,
  config?: { programAddress?: TProgramAddress }
): RequestAccountRotationInstruction<
  TProgramAddress,
  TAccountSender,
  TAccountBump,
  TAccountConfig,
  TAccountUserId,
  TAccountUserRotationState
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sender: { value: input.sender ?? null, isWritable: true },
    bump: { value: input.bump ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    userId: { value: input.userId ?? null, isWritable: false },
    userRotationState: {
      value: input.userRotationState ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.bump),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.userId),
      getAccountMeta(accounts.userRotationState),
    ],
    data: getRequestAccountRotationInstructionDataEncoder().encode(
      args as RequestAccountRotationInstructionDataArgs
    ),
    programAddress,
  } as RequestAccountRotationInstruction<
    TProgramAddress,
    TAccountSender,
    TAccountBump,
    TAccountConfig,
    TAccountUserId,
    TAccountUserRotationState
  >);
}

export type ParsedRequestAccountRotationInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    sender: TAccountMetas[0];
    bump: TAccountMetas[1];
    config: TAccountMetas[2];
    userId: TAccountMetas[3];
    userRotationState: TAccountMetas[4];
  };
  data: RequestAccountRotationInstructionData;
};

export function parseRequestAccountRotationInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedRequestAccountRotationInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      sender: getNextAccount(),
      bump: getNextAccount(),
      config: getNextAccount(),
      userId: getNextAccount(),
      userRotationState: getNextAccount(),
    },
    data: getRequestAccountRotationInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
