/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from 'gill';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getBitFieldDecoder,
  getBitFieldEncoder,
  getRangeDecoder,
  getRangeEncoder,
  getUint32Decoder,
  getUint32Encoder,
  getUint64Decoder,
  getUint64Encoder,
  type BitField,
  type BitFieldArgs,
  type Range,
  type RangeArgs,
  type Uint32,
  type Uint32Args,
  type Uint64,
  type Uint64Args,
} from '../types';

export const UPDATE_CONFIG_DISCRIMINATOR = 1;

export function getUpdateConfigDiscriminatorBytes() {
  return getU8Encoder().encode(UPDATE_CONFIG_DISCRIMINATOR);
}

export type UpdateConfigInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAdminRotationState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAdminRotationState extends string
        ? WritableAccount<TAccountAdminRotationState>
        : TAccountAdminRotationState,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateConfigInstructionData = {
  discriminator: number;
  flags: BitField;
  admin: Address;
  rotationTimeout: Uint32;
  registrationFeeAmount: Uint64;
  dataSizeRange: Range;
};

export type UpdateConfigInstructionDataArgs = {
  flags: BitFieldArgs;
  admin: Address;
  rotationTimeout: Uint32Args;
  registrationFeeAmount: Uint64Args;
  dataSizeRange: RangeArgs;
};

export function getUpdateConfigInstructionDataEncoder(): Encoder<UpdateConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['flags', getBitFieldEncoder()],
      ['admin', getAddressEncoder()],
      ['rotationTimeout', getUint32Encoder()],
      ['registrationFeeAmount', getUint64Encoder()],
      ['dataSizeRange', getRangeEncoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_CONFIG_DISCRIMINATOR })
  );
}

export function getUpdateConfigInstructionDataDecoder(): Decoder<UpdateConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['flags', getBitFieldDecoder()],
    ['admin', getAddressDecoder()],
    ['rotationTimeout', getUint32Decoder()],
    ['registrationFeeAmount', getUint64Decoder()],
    ['dataSizeRange', getRangeDecoder()],
  ]);
}

export function getUpdateConfigInstructionDataCodec(): Codec<
  UpdateConfigInstructionDataArgs,
  UpdateConfigInstructionData
> {
  return combineCodec(
    getUpdateConfigInstructionDataEncoder(),
    getUpdateConfigInstructionDataDecoder()
  );
}

export type UpdateConfigInput<
  TAccountSender extends string = string,
  TAccountConfig extends string = string,
  TAccountAdminRotationState extends string = string,
> = {
  sender: TransactionSigner<TAccountSender>;
  config: Address<TAccountConfig>;
  adminRotationState: Address<TAccountAdminRotationState>;
  flags: UpdateConfigInstructionDataArgs['flags'];
  admin: UpdateConfigInstructionDataArgs['admin'];
  rotationTimeout: UpdateConfigInstructionDataArgs['rotationTimeout'];
  registrationFeeAmount: UpdateConfigInstructionDataArgs['registrationFeeAmount'];
  dataSizeRange: UpdateConfigInstructionDataArgs['dataSizeRange'];
};

export function getUpdateConfigInstruction<
  TAccountSender extends string,
  TAccountConfig extends string,
  TAccountAdminRotationState extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: UpdateConfigInput<
    TAccountSender,
    TAccountConfig,
    TAccountAdminRotationState
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateConfigInstruction<
  TProgramAddress,
  TAccountSender,
  TAccountConfig,
  TAccountAdminRotationState
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sender: { value: input.sender ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    adminRotationState: {
      value: input.adminRotationState ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.adminRotationState),
    ],
    data: getUpdateConfigInstructionDataEncoder().encode(
      args as UpdateConfigInstructionDataArgs
    ),
    programAddress,
  } as UpdateConfigInstruction<
    TProgramAddress,
    TAccountSender,
    TAccountConfig,
    TAccountAdminRotationState
  >);
}

export type ParsedUpdateConfigInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    sender: TAccountMetas[0];
    config: TAccountMetas[1];
    adminRotationState: TAccountMetas[2];
  };
  data: UpdateConfigInstructionData;
};

export function parseUpdateConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      sender: getNextAccount(),
      config: getNextAccount(),
      adminRotationState: getNextAccount(),
    },
    data: getUpdateConfigInstructionDataDecoder().decode(instruction.data),
  };
}
