/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from 'gill';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getBitFieldDecoder,
  getBitFieldEncoder,
  getUint64Decoder,
  getUint64Encoder,
  type BitField,
  type BitFieldArgs,
  type Uint64,
  type Uint64Args,
} from '../types';

export const WITHDRAW_REVENUE_DISCRIMINATOR = 3;

export function getWithdrawRevenueDiscriminatorBytes() {
  return getU8Encoder().encode(WITHDRAW_REVENUE_DISCRIMINATOR);
}

export type WithdrawRevenueInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSystemProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountRecipient extends string | AccountMeta<string> = string,
  TAccountBump extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRevenueMint extends string | AccountMeta<string> = string,
  TAccountRevenueRecipientAta extends string | AccountMeta<string> = string,
  TAccountRevenueAppAta extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountRecipient extends string
        ? WritableAccount<TAccountRecipient>
        : TAccountRecipient,
      TAccountBump extends string
        ? ReadonlyAccount<TAccountBump>
        : TAccountBump,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRevenueMint extends string
        ? ReadonlyAccount<TAccountRevenueMint>
        : TAccountRevenueMint,
      TAccountRevenueRecipientAta extends string
        ? WritableAccount<TAccountRevenueRecipientAta>
        : TAccountRevenueRecipientAta,
      TAccountRevenueAppAta extends string
        ? WritableAccount<TAccountRevenueAppAta>
        : TAccountRevenueAppAta,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawRevenueInstructionData = {
  discriminator: number;
  flags: BitField;
  amount: Uint64;
};

export type WithdrawRevenueInstructionDataArgs = {
  flags: BitFieldArgs;
  amount: Uint64Args;
};

export function getWithdrawRevenueInstructionDataEncoder(): Encoder<WithdrawRevenueInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['flags', getBitFieldEncoder()],
      ['amount', getUint64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: WITHDRAW_REVENUE_DISCRIMINATOR })
  );
}

export function getWithdrawRevenueInstructionDataDecoder(): Decoder<WithdrawRevenueInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['flags', getBitFieldDecoder()],
    ['amount', getUint64Decoder()],
  ]);
}

export function getWithdrawRevenueInstructionDataCodec(): Codec<
  WithdrawRevenueInstructionDataArgs,
  WithdrawRevenueInstructionData
> {
  return combineCodec(
    getWithdrawRevenueInstructionDataEncoder(),
    getWithdrawRevenueInstructionDataDecoder()
  );
}

export type WithdrawRevenueInput<
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSender extends string = string,
  TAccountRecipient extends string = string,
  TAccountBump extends string = string,
  TAccountConfig extends string = string,
  TAccountRevenueMint extends string = string,
  TAccountRevenueRecipientAta extends string = string,
  TAccountRevenueAppAta extends string = string,
> = {
  systemProgram: Address<TAccountSystemProgram>;
  tokenProgram: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  sender: TransactionSigner<TAccountSender>;
  recipient: Address<TAccountRecipient>;
  bump: Address<TAccountBump>;
  config: Address<TAccountConfig>;
  revenueMint: Address<TAccountRevenueMint>;
  revenueRecipientAta: Address<TAccountRevenueRecipientAta>;
  revenueAppAta: Address<TAccountRevenueAppAta>;
  flags: WithdrawRevenueInstructionDataArgs['flags'];
  amount: WithdrawRevenueInstructionDataArgs['amount'];
};

export function getWithdrawRevenueInstruction<
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSender extends string,
  TAccountRecipient extends string,
  TAccountBump extends string,
  TAccountConfig extends string,
  TAccountRevenueMint extends string,
  TAccountRevenueRecipientAta extends string,
  TAccountRevenueAppAta extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: WithdrawRevenueInput<
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSender,
    TAccountRecipient,
    TAccountBump,
    TAccountConfig,
    TAccountRevenueMint,
    TAccountRevenueRecipientAta,
    TAccountRevenueAppAta
  >,
  config?: { programAddress?: TProgramAddress }
): WithdrawRevenueInstruction<
  TProgramAddress,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSender,
  TAccountRecipient,
  TAccountBump,
  TAccountConfig,
  TAccountRevenueMint,
  TAccountRevenueRecipientAta,
  TAccountRevenueAppAta
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    sender: { value: input.sender ?? null, isWritable: true },
    recipient: { value: input.recipient ?? null, isWritable: true },
    bump: { value: input.bump ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    revenueMint: { value: input.revenueMint ?? null, isWritable: false },
    revenueRecipientAta: {
      value: input.revenueRecipientAta ?? null,
      isWritable: true,
    },
    revenueAppAta: { value: input.revenueAppAta ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.recipient),
      getAccountMeta(accounts.bump),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.revenueMint),
      getAccountMeta(accounts.revenueRecipientAta),
      getAccountMeta(accounts.revenueAppAta),
    ],
    data: getWithdrawRevenueInstructionDataEncoder().encode(
      args as WithdrawRevenueInstructionDataArgs
    ),
    programAddress,
  } as WithdrawRevenueInstruction<
    TProgramAddress,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSender,
    TAccountRecipient,
    TAccountBump,
    TAccountConfig,
    TAccountRevenueMint,
    TAccountRevenueRecipientAta,
    TAccountRevenueAppAta
  >);
}

export type ParsedWithdrawRevenueInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    systemProgram: TAccountMetas[0];
    tokenProgram: TAccountMetas[1];
    associatedTokenProgram: TAccountMetas[2];
    sender: TAccountMetas[3];
    recipient: TAccountMetas[4];
    bump: TAccountMetas[5];
    config: TAccountMetas[6];
    revenueMint: TAccountMetas[7];
    revenueRecipientAta: TAccountMetas[8];
    revenueAppAta: TAccountMetas[9];
  };
  data: WithdrawRevenueInstructionData;
};

export function parseWithdrawRevenueInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedWithdrawRevenueInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      sender: getNextAccount(),
      recipient: getNextAccount(),
      bump: getNextAccount(),
      config: getNextAccount(),
      revenueMint: getNextAccount(),
      revenueRecipientAta: getNextAccount(),
      revenueAppAta: getNextAccount(),
    },
    data: getWithdrawRevenueInstructionDataDecoder().decode(instruction.data),
  };
}
