/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from 'gill';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getString4096Decoder,
  getString4096Encoder,
  getUint64Decoder,
  getUint64Encoder,
  type String4096,
  type String4096Args,
  type Uint64,
  type Uint64Args,
} from '../types';

export const WRITE_DATA_DISCRIMINATOR = 8;

export function getWriteDataDiscriminatorBytes() {
  return getU8Encoder().encode(WRITE_DATA_DISCRIMINATOR);
}

export type WriteDataInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountUserId extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountUserId extends string
        ? ReadonlyAccount<TAccountUserId>
        : TAccountUserId,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      ...TRemainingAccounts,
    ]
  >;

export type WriteDataInstructionData = {
  discriminator: number;
  data: String4096;
  nonce: Uint64;
};

export type WriteDataInstructionDataArgs = {
  data: String4096Args;
  nonce: Uint64Args;
};

export function getWriteDataInstructionDataEncoder(): Encoder<WriteDataInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['data', getString4096Encoder()],
      ['nonce', getUint64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: WRITE_DATA_DISCRIMINATOR })
  );
}

export function getWriteDataInstructionDataDecoder(): Decoder<WriteDataInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['data', getString4096Decoder()],
    ['nonce', getUint64Decoder()],
  ]);
}

export function getWriteDataInstructionDataCodec(): Codec<
  WriteDataInstructionDataArgs,
  WriteDataInstructionData
> {
  return combineCodec(
    getWriteDataInstructionDataEncoder(),
    getWriteDataInstructionDataDecoder()
  );
}

export type WriteDataInput<
  TAccountSender extends string = string,
  TAccountUserId extends string = string,
  TAccountUserAccount extends string = string,
> = {
  sender: TransactionSigner<TAccountSender>;
  userId: Address<TAccountUserId>;
  userAccount: Address<TAccountUserAccount>;
  data: WriteDataInstructionDataArgs['data'];
  nonce: WriteDataInstructionDataArgs['nonce'];
};

export function getWriteDataInstruction<
  TAccountSender extends string,
  TAccountUserId extends string,
  TAccountUserAccount extends string,
  TProgramAddress extends Address = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
>(
  input: WriteDataInput<TAccountSender, TAccountUserId, TAccountUserAccount>,
  config?: { programAddress?: TProgramAddress }
): WriteDataInstruction<
  TProgramAddress,
  TAccountSender,
  TAccountUserId,
  TAccountUserAccount
> {
  // Program address.
  const programAddress = config?.programAddress ?? REGISTRY_CPI_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sender: { value: input.sender ?? null, isWritable: true },
    userId: { value: input.userId ?? null, isWritable: false },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.userId),
      getAccountMeta(accounts.userAccount),
    ],
    data: getWriteDataInstructionDataEncoder().encode(
      args as WriteDataInstructionDataArgs
    ),
    programAddress,
  } as WriteDataInstruction<
    TProgramAddress,
    TAccountSender,
    TAccountUserId,
    TAccountUserAccount
  >);
}

export type ParsedWriteDataInstruction<
  TProgram extends string = typeof REGISTRY_CPI_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    sender: TAccountMetas[0];
    userId: TAccountMetas[1];
    userAccount: TAccountMetas[2];
  };
  data: WriteDataInstructionData;
};

export function parseWriteDataInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedWriteDataInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      sender: getNextAccount(),
      userId: getNextAccount(),
      userAccount: getNextAccount(),
    },
    data: getWriteDataInstructionDataDecoder().decode(instruction.data),
  };
}
