/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { type Address } from '@solana/kit';

export const REGISTRY_CPI_PROGRAM_ADDRESS =
  '89KoDhPxWcegVeGrr8sAg3sn7H7EaH6edtDg9qx8Jh19' as Address<'89KoDhPxWcegVeGrr8sAg3sn7H7EaH6edtDg9qx8Jh19'>;

export enum RegistryCpiAccount {
  Bump,
  Config,
  UserCounter,
  RotationState,
  UserId,
  UserAccount,
}
