[package]
name = "tests"
version = "1.0.0"
description = "litesvm tests"
repository = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
std = []

[dependencies]
pinocchio = { workspace = true }
pinocchio-pubkey = { workspace = true }
pinocchio-associated-token-account = { workspace = true }
pinocchio-log = { workspace = true }
pinocchio-system = { workspace = true }
pinocchio-token = { workspace = true }

serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
pretty_assertions = { workspace = true }
litesvm = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-message = { workspace = true }
solana-pubkey = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { workspace = true }
solana-system-program = { workspace = true }
solana-program = { workspace = true }
solana-compute-budget = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true }
solana-kite = { workspace = true }

# dev feature is required for test helpers
base = { workspace = true, features = ["dev"] }
registry-cpi = { workspace = true, features = ["dev"] }

registry = { workspace = true }
