/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from 'gill';

export type Bump = {
  config: number;
  userCounter: number;
  rotationState: number;
};

export type BumpArgs = Bump;

export function getBumpEncoder(): FixedSizeEncoder<BumpArgs> {
  return getStructEncoder([
    ['config', getU8Encoder()],
    ['userCounter', getU8Encoder()],
    ['rotationState', getU8Encoder()],
  ]);
}

export function getBumpDecoder(): FixedSizeDecoder<Bump> {
  return getStructDecoder([
    ['config', getU8Decoder()],
    ['userCounter', getU8Decoder()],
    ['rotationState', getU8Decoder()],
  ]);
}

export function getBumpCodec(): FixedSizeCodec<BumpArgs, Bump> {
  return combineCodec(getBumpEncoder(), getBumpDecoder());
}

export function decodeBump<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Bump, TAddress>;
export function decodeBump<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Bump, TAddress>;
export function decodeBump<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Bump, TAddress> | MaybeAccount<Bump, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBumpDecoder()
  );
}

export async function fetchBump<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Bump, TAddress>> {
  const maybeAccount = await fetchMaybeBump(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBump<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Bump, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBump(maybeAccount);
}

export async function fetchAllBump(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Bump>[]> {
  const maybeAccounts = await fetchAllMaybeBump(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBump(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Bump>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeBump(maybeAccount));
}
