/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from 'gill';
import {
  getUint64Decoder,
  getUint64Encoder,
  type Uint64,
  type Uint64Args,
} from '../types';

export type RotationState = {
  owner: Address;
  newOwner: Address;
  expirationDate: Uint64;
};

export type RotationStateArgs = {
  owner: Address;
  newOwner: Address;
  expirationDate: Uint64Args;
};

export function getRotationStateEncoder(): Encoder<RotationStateArgs> {
  return getStructEncoder([
    ['owner', getAddressEncoder()],
    ['newOwner', getAddressEncoder()],
    ['expirationDate', getUint64Encoder()],
  ]);
}

export function getRotationStateDecoder(): Decoder<RotationState> {
  return getStructDecoder([
    ['owner', getAddressDecoder()],
    ['newOwner', getAddressDecoder()],
    ['expirationDate', getUint64Decoder()],
  ]);
}

export function getRotationStateCodec(): Codec<
  RotationStateArgs,
  RotationState
> {
  return combineCodec(getRotationStateEncoder(), getRotationStateDecoder());
}

export function decodeRotationState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<RotationState, TAddress>;
export function decodeRotationState<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<RotationState, TAddress>;
export function decodeRotationState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<RotationState, TAddress> | MaybeAccount<RotationState, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRotationStateDecoder()
  );
}

export async function fetchRotationState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<RotationState, TAddress>> {
  const maybeAccount = await fetchMaybeRotationState(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRotationState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<RotationState, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRotationState(maybeAccount);
}

export async function fetchAllRotationState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<RotationState>[]> {
  const maybeAccounts = await fetchAllMaybeRotationState(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRotationState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<RotationState>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeRotationState(maybeAccount));
}
