/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getStructDecoder,
  getStructEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/kit';
import {
  getUint32Decoder,
  getUint32Encoder,
  type Uint32,
  type Uint32Args,
} from '../types';

export type UserCounter = { lastUserId: Uint32 };

export type UserCounterArgs = { lastUserId: Uint32Args };

export function getUserCounterEncoder(): Encoder<UserCounterArgs> {
  return getStructEncoder([['lastUserId', getUint32Encoder()]]);
}

export function getUserCounterDecoder(): Decoder<UserCounter> {
  return getStructDecoder([['lastUserId', getUint32Decoder()]]);
}

export function getUserCounterCodec(): Codec<UserCounterArgs, UserCounter> {
  return combineCodec(getUserCounterEncoder(), getUserCounterDecoder());
}

export function decodeUserCounter<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<UserCounter, TAddress>;
export function decodeUserCounter<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<UserCounter, TAddress>;
export function decodeUserCounter<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<UserCounter, TAddress> | MaybeAccount<UserCounter, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserCounterDecoder()
  );
}

export async function fetchUserCounter<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<UserCounter, TAddress>> {
  const maybeAccount = await fetchMaybeUserCounter(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserCounter<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<UserCounter, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserCounter(maybeAccount);
}

export async function fetchAllUserCounter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<UserCounter>[]> {
  const maybeAccounts = await fetchAllMaybeUserCounter(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserCounter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<UserCounter>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeUserCounter(maybeAccount));
}
