/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/kit';
import {
  getBitFieldDecoder,
  getBitFieldEncoder,
  getUint32Decoder,
  getUint32Encoder,
  type BitField,
  type BitFieldArgs,
  type Uint32,
  type Uint32Args,
} from '../types';

export type UserId = {
  flags: BitField;
  id: Uint32;
  accountBump: number;
  rotationStateBump: number;
};

export type UserIdArgs = {
  flags: BitFieldArgs;
  id: Uint32Args;
  accountBump: number;
  rotationStateBump: number;
};

export function getUserIdEncoder(): Encoder<UserIdArgs> {
  return getStructEncoder([
    ['flags', getBitFieldEncoder()],
    ['id', getUint32Encoder()],
    ['accountBump', getU8Encoder()],
    ['rotationStateBump', getU8Encoder()],
  ]);
}

export function getUserIdDecoder(): Decoder<UserId> {
  return getStructDecoder([
    ['flags', getBitFieldDecoder()],
    ['id', getUint32Decoder()],
    ['accountBump', getU8Decoder()],
    ['rotationStateBump', getU8Decoder()],
  ]);
}

export function getUserIdCodec(): Codec<UserIdArgs, UserId> {
  return combineCodec(getUserIdEncoder(), getUserIdDecoder());
}

export function decodeUserId<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<UserId, TAddress>;
export function decodeUserId<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<UserId, TAddress>;
export function decodeUserId<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<UserId, TAddress> | MaybeAccount<UserId, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserIdDecoder()
  );
}

export async function fetchUserId<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<UserId, TAddress>> {
  const maybeAccount = await fetchMaybeUserId(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserId<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<UserId, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserId(maybeAccount);
}

export async function fetchAllUserId(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<UserId>[]> {
  const maybeAccounts = await fetchAllMaybeUserId(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserId(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<UserId>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeUserId(maybeAccount));
}
