/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from 'gill';
import {
  getUint32Decoder,
  getUint32Encoder,
  getUint64Decoder,
  getUint64Encoder,
  type Uint32,
  type Uint32Args,
  type Uint64,
  type Uint64Args,
} from '../types';

export type UserAccount = {
  data: Array<number>;
  nonce: Uint64;
  maxSize: Uint32;
};

export type UserAccountArgs = {
  data: Array<number>;
  nonce: Uint64Args;
  maxSize: Uint32Args;
};

export function getUserAccountEncoder(): Encoder<UserAccountArgs> {
  return getStructEncoder([
    ['data', getArrayEncoder(getU8Encoder(), { size: 4096 })],
    ['nonce', getUint64Encoder()],
    ['maxSize', getUint32Encoder()],
  ]);
}

export function getUserAccountDecoder(): Decoder<UserAccount> {
  return getStructDecoder([
    ['data', getArrayDecoder(getU8Decoder(), { size: 4096 })],
    ['nonce', getUint64Decoder()],
    ['maxSize', getUint32Decoder()],
  ]);
}

export function getUserAccountCodec(): Codec<UserAccountArgs, UserAccount> {
  return combineCodec(getUserAccountEncoder(), getUserAccountDecoder());
}

export function decodeUserAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<UserAccount, TAddress>;
export function decodeUserAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<UserAccount, TAddress>;
export function decodeUserAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<UserAccount, TAddress> | MaybeAccount<UserAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserAccountDecoder()
  );
}

export async function fetchUserAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<UserAccount, TAddress>> {
  const maybeAccount = await fetchMaybeUserAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<UserAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserAccount(maybeAccount);
}

export async function fetchAllUserAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<UserAccount>[]> {
  const maybeAccounts = await fetchAllMaybeUserAccount(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<UserAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeUserAccount(maybeAccount));
}
