/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { BASE_PROGRAM_ADDRESS } from '../programs';

export const BASE_ERROR__UNAUTHORIZED = 0x0; // 0
export const BASE_ERROR__NO_NEW_OWNER = 0x1; // 1
export const BASE_ERROR__USELESS_ROTATION = 0x2; // 2
export const BASE_ERROR__TRANSFER_OWNER_DEADLINE = 0x3; // 3

export type BaseError =
  | typeof BASE_ERROR__NO_NEW_OWNER
  | typeof BASE_ERROR__TRANSFER_OWNER_DEADLINE
  | typeof BASE_ERROR__UNAUTHORIZED
  | typeof BASE_ERROR__USELESS_ROTATION;

let baseErrorMessages: Record<BaseError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  baseErrorMessages = {
    [BASE_ERROR__NO_NEW_OWNER]: `New owner wasn't specified!`,
    [BASE_ERROR__TRANSFER_OWNER_DEADLINE]: `It's too late to accept owner role!`,
    [BASE_ERROR__UNAUTHORIZED]: `Sender doesn't have access permissions!`,
    [BASE_ERROR__USELESS_ROTATION]: `Sender can't be the new owner!`,
  };
}

export function getBaseErrorMessage(code: BaseError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (baseErrorMessages as Record<BaseError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isBaseError<TProgramErrorCode extends BaseError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    BASE_PROGRAM_ADDRESS,
    code
  );
}
