/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { REGISTRY_CPI_PROGRAM_ADDRESS } from '../programs';

export const REGISTRY_CPI_ERROR__NO_PARAMETERS = 0x0; // 0
export const REGISTRY_CPI_ERROR__WRONG_ASSET_TYPE = 0x1; // 1
export const REGISTRY_CPI_ERROR__ZERO_AMOUNT = 0x2; // 2
export const REGISTRY_CPI_ERROR__EXCEEDED_AVAILABLE_ASSET_AMOUNT = 0x3; // 3
export const REGISTRY_CPI_ERROR__CONTRACT_IS_PAUSED = 0x4; // 4
export const REGISTRY_CPI_ERROR__MAX_DATA_SIZE_IS_OUT_OF_RANGE = 0x5; // 5
export const REGISTRY_CPI_ERROR__MAX_DATA_SIZE_IS_EXCEEDED = 0x6; // 6
export const REGISTRY_CPI_ERROR__WRONG_USER_ID = 0x7; // 7
export const REGISTRY_CPI_ERROR__ACTIVATE_ACCOUNT_TWICE = 0x8; // 8
export const REGISTRY_CPI_ERROR__ACCOUNT_IS_NOT_ACTIVATED = 0x9; // 9
export const REGISTRY_CPI_ERROR__OPEN_ACCOUNT_TWICE = 0xa; // 10
export const REGISTRY_CPI_ERROR__ACCOUNT_IS_NOT_OPENED = 0xb; // 11
export const REGISTRY_CPI_ERROR__BAD_NONCE = 0xc; // 12

export type RegistryCpiError =
  | typeof REGISTRY_CPI_ERROR__ACCOUNT_IS_NOT_ACTIVATED
  | typeof REGISTRY_CPI_ERROR__ACCOUNT_IS_NOT_OPENED
  | typeof REGISTRY_CPI_ERROR__ACTIVATE_ACCOUNT_TWICE
  | typeof REGISTRY_CPI_ERROR__BAD_NONCE
  | typeof REGISTRY_CPI_ERROR__CONTRACT_IS_PAUSED
  | typeof REGISTRY_CPI_ERROR__EXCEEDED_AVAILABLE_ASSET_AMOUNT
  | typeof REGISTRY_CPI_ERROR__MAX_DATA_SIZE_IS_EXCEEDED
  | typeof REGISTRY_CPI_ERROR__MAX_DATA_SIZE_IS_OUT_OF_RANGE
  | typeof REGISTRY_CPI_ERROR__NO_PARAMETERS
  | typeof REGISTRY_CPI_ERROR__OPEN_ACCOUNT_TWICE
  | typeof REGISTRY_CPI_ERROR__WRONG_ASSET_TYPE
  | typeof REGISTRY_CPI_ERROR__WRONG_USER_ID
  | typeof REGISTRY_CPI_ERROR__ZERO_AMOUNT;

let registryCpiErrorMessages: Record<RegistryCpiError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  registryCpiErrorMessages = {
    [REGISTRY_CPI_ERROR__ACCOUNT_IS_NOT_ACTIVATED]: `Account isn't activated!`,
    [REGISTRY_CPI_ERROR__ACCOUNT_IS_NOT_OPENED]: `Account isn't opened!`,
    [REGISTRY_CPI_ERROR__ACTIVATE_ACCOUNT_TWICE]: `Account can't be activated twice!`,
    [REGISTRY_CPI_ERROR__BAD_NONCE]: `Nonce must be unique!`,
    [REGISTRY_CPI_ERROR__CONTRACT_IS_PAUSED]: `The contract is temporary paused!`,
    [REGISTRY_CPI_ERROR__EXCEEDED_AVAILABLE_ASSET_AMOUNT]: `Exceeded available asset amount!`,
    [REGISTRY_CPI_ERROR__MAX_DATA_SIZE_IS_EXCEEDED]: `Max data size is exceeded!`,
    [REGISTRY_CPI_ERROR__MAX_DATA_SIZE_IS_OUT_OF_RANGE]: `Max data size is out of range!`,
    [REGISTRY_CPI_ERROR__NO_PARAMETERS]: `Parameters are not provided!`,
    [REGISTRY_CPI_ERROR__OPEN_ACCOUNT_TWICE]: `Account can't be opened twice!`,
    [REGISTRY_CPI_ERROR__WRONG_ASSET_TYPE]: `Wrong asset type!`,
    [REGISTRY_CPI_ERROR__WRONG_USER_ID]: `Wrong user ID!`,
    [REGISTRY_CPI_ERROR__ZERO_AMOUNT]: `Zero amount to send!`,
  };
}

export function getRegistryCpiErrorMessage(code: RegistryCpiError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (registryCpiErrorMessages as Record<RegistryCpiError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isRegistryCpiError<TProgramErrorCode extends RegistryCpiError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    REGISTRY_CPI_PROGRAM_ADDRESS,
    code
  );
}
