/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from 'gill';
import {
  getUint64Decoder,
  getUint64Encoder,
  type Uint64,
  type Uint64Args,
} from '.';

export type AssetItem = { amount: Uint64; asset: Address };

export type AssetItemArgs = { amount: Uint64Args; asset: Address };

export function getAssetItemEncoder(): Encoder<AssetItemArgs> {
  return getStructEncoder([
    ['amount', getUint64Encoder()],
    ['asset', getAddressEncoder()],
  ]);
}

export function getAssetItemDecoder(): Decoder<AssetItem> {
  return getStructDecoder([
    ['amount', getUint64Decoder()],
    ['asset', getAddressDecoder()],
  ]);
}

export function getAssetItemCodec(): Codec<AssetItemArgs, AssetItem> {
  return combineCodec(getAssetItemEncoder(), getAssetItemDecoder());
}
