/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type BitField = number;

export type BitFieldArgs = BitField;

export function getBitFieldEncoder(): FixedSizeEncoder<BitFieldArgs> {
  return getU8Encoder();
}

export function getBitFieldDecoder(): FixedSizeDecoder<BitField> {
  return getU8Decoder();
}

export function getBitFieldCodec(): FixedSizeCodec<BitFieldArgs, BitField> {
  return combineCodec(getBitFieldEncoder(), getBitFieldDecoder());
}
