/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getUint32Decoder,
  getUint32Encoder,
  type Uint32,
  type Uint32Args,
} from '.';

export type Range = { min: Uint32; max: Uint32 };

export type RangeArgs = { min: Uint32Args; max: Uint32Args };

export function getRangeEncoder(): Encoder<RangeArgs> {
  return getStructEncoder([
    ['min', getUint32Encoder()],
    ['max', getUint32Encoder()],
  ]);
}

export function getRangeDecoder(): Decoder<Range> {
  return getStructDecoder([
    ['min', getUint32Decoder()],
    ['max', getUint32Decoder()],
  ]);
}

export function getRangeCodec(): Codec<RangeArgs, Range> {
  return combineCodec(getRangeEncoder(), getRangeDecoder());
}
