/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type String64 = Array<number>;

export type String64Args = String64;

export function getString64Encoder(): FixedSizeEncoder<String64Args> {
  return getArrayEncoder(getU8Encoder(), { size: 64 });
}

export function getString64Decoder(): FixedSizeDecoder<String64> {
  return getArrayDecoder(getU8Decoder(), { size: 64 });
}

export function getString64Codec(): FixedSizeCodec<String64Args, String64> {
  return combineCodec(getString64Encoder(), getString64Decoder());
}
