/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type String4096 = Array<number>;

export type String4096Args = String4096;

export function getString4096Encoder(): FixedSizeEncoder<String4096Args> {
  return getArrayEncoder(getU8Encoder(), { size: 4096 });
}

export function getString4096Decoder(): FixedSizeDecoder<String4096> {
  return getArrayDecoder(getU8Decoder(), { size: 4096 });
}

export function getString4096Codec(): FixedSizeCodec<
  String4096Args,
  String4096
> {
  return combineCodec(getString4096Encoder(), getString4096Decoder());
}
