/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type String16 = Array<number>;

export type String16Args = String16;

export function getString16Encoder(): FixedSizeEncoder<String16Args> {
  return getArrayEncoder(getU8Encoder(), { size: 16 });
}

export function getString16Decoder(): FixedSizeDecoder<String16> {
  return getArrayDecoder(getU8Decoder(), { size: 16 });
}

export function getString16Codec(): FixedSizeCodec<String16Args, String16> {
  return combineCodec(getString16Encoder(), getString16Decoder());
}
