/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type String32 = Array<number>;

export type String32Args = String32;

export function getString32Encoder(): FixedSizeEncoder<String32Args> {
  return getArrayEncoder(getU8Encoder(), { size: 32 });
}

export function getString32Decoder(): FixedSizeDecoder<String32> {
  return getArrayDecoder(getU8Decoder(), { size: 32 });
}

export function getString32Codec(): FixedSizeCodec<String32Args, String32> {
  return combineCodec(getString32Encoder(), getString32Decoder());
}
