/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type StructWithArray = { list: Array<number> };

export type StructWithArrayArgs = StructWithArray;

export function getStructWithArrayEncoder(): FixedSizeEncoder<StructWithArrayArgs> {
  return getStructEncoder([
    ['list', getArrayEncoder(getU16Encoder(), { size: 5 })],
  ]);
}

export function getStructWithArrayDecoder(): FixedSizeDecoder<StructWithArray> {
  return getStructDecoder([
    ['list', getArrayDecoder(getU16Decoder(), { size: 5 })],
  ]);
}

export function getStructWithArrayCodec(): FixedSizeCodec<
  StructWithArrayArgs,
  StructWithArray
> {
  return combineCodec(getStructWithArrayEncoder(), getStructWithArrayDecoder());
}
