/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from 'gill';
import {
  getTargetEnumDecoder,
  getTargetEnumEncoder,
  getUint32Decoder,
  getUint32Encoder,
  type TargetEnum,
  type TargetEnumArgs,
  type Uint32,
  type Uint32Args,
} from '.';

export type StructWithEnum = { num: Uint32; target: TargetEnum };

export type StructWithEnumArgs = { num: Uint32Args; target: TargetEnumArgs };

export function getStructWithEnumEncoder(): Encoder<StructWithEnumArgs> {
  return getStructEncoder([
    ['num', getUint32Encoder()],
    ['target', getTargetEnumEncoder()],
  ]);
}

export function getStructWithEnumDecoder(): Decoder<StructWithEnum> {
  return getStructDecoder([
    ['num', getUint32Decoder()],
    ['target', getTargetEnumDecoder()],
  ]);
}

export function getStructWithEnumCodec(): Codec<
  StructWithEnumArgs,
  StructWithEnum
> {
  return combineCodec(getStructWithEnumEncoder(), getStructWithEnumDecoder());
}
