/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type TargetEnum = number;

export type TargetEnumArgs = TargetEnum;

export function getTargetEnumEncoder(): FixedSizeEncoder<TargetEnumArgs> {
  return getU8Encoder();
}

export function getTargetEnumDecoder(): FixedSizeDecoder<TargetEnum> {
  return getU8Decoder();
}

export function getTargetEnumCodec(): FixedSizeCodec<
  TargetEnumArgs,
  TargetEnum
> {
  return combineCodec(getTargetEnumEncoder(), getTargetEnumDecoder());
}
