/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export enum Target {
  Spl,
  Proxy,
  Route,
}

export type TargetArgs = Target;

export function getTargetEncoder(): FixedSizeEncoder<TargetArgs> {
  return getEnumEncoder(Target);
}

export function getTargetDecoder(): FixedSizeDecoder<Target> {
  return getEnumDecoder(Target);
}

export function getTargetCodec(): FixedSizeCodec<TargetArgs, Target> {
  return combineCodec(getTargetEncoder(), getTargetDecoder());
}
