/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type Uint128 = Array<number>;

export type Uint128Args = Uint128;

export function getUint128Encoder(): FixedSizeEncoder<Uint128Args> {
  return getArrayEncoder(getU8Encoder(), { size: 16 });
}

export function getUint128Decoder(): FixedSizeDecoder<Uint128> {
  return getArrayDecoder(getU8Decoder(), { size: 16 });
}

export function getUint128Codec(): FixedSizeCodec<Uint128Args, Uint128> {
  return combineCodec(getUint128Encoder(), getUint128Decoder());
}
