/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type Uint16 = Array<number>;

export type Uint16Args = Uint16;

export function getUint16Encoder(): FixedSizeEncoder<Uint16Args> {
  return getArrayEncoder(getU8Encoder(), { size: 2 });
}

export function getUint16Decoder(): FixedSizeDecoder<Uint16> {
  return getArrayDecoder(getU8Decoder(), { size: 2 });
}

export function getUint16Codec(): FixedSizeCodec<Uint16Args, Uint16> {
  return combineCodec(getUint16Encoder(), getUint16Decoder());
}
