/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type Uint32 = Array<number>;

export type Uint32Args = Uint32;

export function getUint32Encoder(): FixedSizeEncoder<Uint32Args> {
  return getArrayEncoder(getU8Encoder(), { size: 4 });
}

export function getUint32Decoder(): FixedSizeDecoder<Uint32> {
  return getArrayDecoder(getU8Decoder(), { size: 4 });
}

export function getUint32Codec(): FixedSizeCodec<Uint32Args, Uint32> {
  return combineCodec(getUint32Encoder(), getUint32Decoder());
}
