/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from 'gill';

export type Uint64 = Array<number>;

export type Uint64Args = Uint64;

export function getUint64Encoder(): FixedSizeEncoder<Uint64Args> {
  return getArrayEncoder(getU8Encoder(), { size: 8 });
}

export function getUint64Decoder(): FixedSizeDecoder<Uint64> {
  return getArrayDecoder(getU8Decoder(), { size: 8 });
}

export function getUint64Codec(): FixedSizeCodec<Uint64Args, Uint64> {
  return combineCodec(getUint64Encoder(), getUint64Decoder());
}
