[package]
name = "registry"
version = "1.0.0"
description = "Pinocchio registry"
repository = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
std = []

[dependencies]
pinocchio = { workspace = true }
pinocchio-pubkey = { workspace = true }
pinocchio-log = { workspace = true }
bytemuck = { workspace = true }
shank = { workspace = true }

base = { workspace = true }
macro-error = { workspace = true }
registry-cpi = { workspace = true }
